### ISSUE TITLE
Practice Lab 1 - Creating cases - missing instructions

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-230-Dynamics365forCustomerService#73]
# Module: 01
#### Step: 04

Description of issue
* on the subject field, there is no existing subject for Service and Maintenance. it has be created first to be available for selection. I know how to do this, but please include instructions on how to create it for learners or have it available as part of the sample data.

#### Step: 07

Description of issue
* there are no active products in the environment. JBO top D Hifi needs to be created from scratch. I know how to do this, but please include instructions on how to create it for learners or have it available as part of the sample data.

**Comment by MVPMarcondesAlexandre** [comment]
Resolution for issue - Step 07
You need to access https://make.powerapps.com/environments and change your environment for instance to: WWWCLOUDCE000103, according to the picture below.

![image](https://github.com/MicrosoftLearning/MB-230-Dynamics365forCustomerService/assets/29643911/684c7bc8-95cc-46d5-87f6-c4ea9d21919f)

Now, click on the **Tables** option on the left side of the site, for later on the search field you enter with table name : Product, according to the picture below.
![image](https://github.com/MicrosoftLearning/MB-230-Dynamics365forCustomerService/assets/29643911/8072f8be-40d0-4f2f-ad3f-11b459d09570)

Select Product table and after click on the option Publish, so that you can view the product on the case in Dynamic 365 Customer Service that you are creating. 
![image](https://github.com/MicrosoftLearning/MB-230-Dynamics365forCustomerService/assets/29643911/262ddd24-c3f2-4a65-8571-a2c60e6f91e3)

Back to Customer Service Hub on the page for Creating Case and Product field , click on Lookup icon and select the JBO Top. D. Hifi product.
![image](https://github.com/MicrosoftLearning/MB-230-Dynamics365forCustomerService/assets/29643911/8c1398f8-3bbf-4d06-8e7f-d20e75359251)

**Comment by anjenni** [comment]
Hi there! Thanks so much for bringing this to our attention. Just letting you know that tomorrow (6/9) we will be implementing an update that will include a new instructor demo to create the necessary demo data. Thanks again for logging this and I'll close it out tomorrow. Let me know if anything else comes up.

**Comment by anjenni** [comment]
Hi there! We just pushed an update that includes a new instructor demo to create and publish the demo data. Please let me know if any further issues arise. I am closing out this issue.
